name: Moments
favicon: null
layout_spectrum: 0.39200711948797107
typography_spectrum: 0.896853115176782
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#04030c'
    - '#eef0d6'
    - '#bbb695'
    - '#3b3232'
    - '#736155'
  brandStrength: 0
  lightness: 0.3125
  saturation: 1
  rhythmicContrast: 0
purpose: []
