name: Moments
favicon: null
layout_spectrum: 0.39200711948797107
typography_spectrum: 0.896853115176782
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.32390088331885636
  lightness: 0.13337061111815274
  saturation: 0.6026752670295537
  rhythmicContrast: 0.016917596803978086
purpose: []
